### ISSUE TITLE
Improve pre-push hook to handle known vulnerabilities

### ISSUE THREAD

**Issue by aRustyDev** [aRustyDev/quizlr#22]
## Problem
The pre-push hook fails when there are security vulnerabilities reported by cargo audit, even when there's no fix available. This blocks pushing code changes.

## Current Behavior
- Pre-push hook runs cargo audit
- If any vulnerabilities are found, the push is blocked
- Even if vulnerabilities have no available fix, push is still blocked

## Proposed Solution
1. Maintain an allow-list of known vulnerabilities that have no fix
2. Only block push for new/unknown vulnerabilities
3. Add a warning for allowed vulnerabilities
4. Document the process for adding vulnerabilities to the allow-list

## Example Implementation
Create a `.cargo/audit.toml` file:
```toml
[advisories]
ignore = [
    "RUSTSEC-2023-0071", # RSA timing sidechannel - no fix available yet
]
```

## Benefits
- Developers can continue working while waiting for upstream fixes
- Still alerts on new vulnerabilities
- Maintains security awareness without blocking productivity
